# Generated by Django 3.2.16 on 2023-06-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_perso', '0003_profiletitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='fin',
            field=models.DateField(blank=True, null=True, verbose_name='date fin'),
        ),
    ]
