# Generated by Django 3.2.16 on 2023-06-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_perso', '0004_alter_experience_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletitle',
            name='profile',
            field=models.TextField(blank=True, null=True, verbose_name='Profile'),
        ),
    ]
