# Generated by Django 3.2.16 on 2023-06-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_perso', '0005_profiletitle_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='debut',
            field=models.DateField(blank=True, null=True, verbose_name='date de debut'),
        ),
        migrations.DeleteModel(
            name='ProfileText',
        ),
    ]
