# Generated by Django 3.2.16 on 2023-07-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_perso', '0008_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Status matrimonial'),
        ),
    ]
