# Generated by Django 3.2.16 on 2023-07-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_perso', '0009_cv_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='telephone_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='status',
            field=models.CharField(blank=True, choices=[('Celibataire', 'Celibataire'), ('Marié', 'Marié'), ('Divorcé', 'Divorcé')], max_length=250, null=True, verbose_name='Status matrimonial'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='entreprise',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ville',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
