# Generated by Django 3.2.16 on 2023-08-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_perso', '0010_auto_20230705_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero Telephone'),
        ),
        migrations.AlterField(
            model_name='social',
            name='social',
            field=models.CharField(blank=True, choices=[('whatsapp', 'Whatsapp'), ('facebook', 'Facebook'), ('lindln', 'Lindln'), ('instagram', 'Instagram'), ('twitter', 'Twitter')], max_length=50, null=True),
        ),
    ]
